import { ConnectButton } from "@rainbow-me/rainbowkit";
import type { NextPage } from "next";
import Head from "next/head";
import styles from "../styles/Home.module.css";
import HeroImage from "../components/hero-image/hero";
import Upload from "../components/upload/Upload";
import Play from "../components/upload/Play";
const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Tokyo Sounds</title>
        <meta
          content="Generated by @rainbow-me/create-rainbowkit"
          name="description"
        />
        <link href="/favicon.ico" rel="icon" />
      </Head>
      <HeroImage></HeroImage>
      <main className={styles.main}>
        <h1 className={styles.title}>Welcome to Tokyo Sounds</h1>

        <p className={styles.description}>
          {/* Get started by editing{" "}
          <code className={styles.code}>pages/index.tsx</code> */}
        </p>

        <div className={styles.grid}>
          <a className={styles.card} href="https://rainbowkit.com">
            <h2>Use case 1 &rarr;</h2>
            <p>Encrypt your music</p>
          </a>

          <a className={styles.card} href="https://wagmi.sh">
            <h2>Use case 2 &rarr;</h2>
            <p>Decrypt and play your music</p>
          </a>
        </div>

        <div id="encrypt__section" className="Sections">
          <Upload></Upload>
        </div>
        <div id="decrypt__section" className="Sections">
          <Play></Play>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://www.ethglobal.com"
          rel="noopener noreferrer"
          target="_blank"
        >
          Made with ❤️ at ETHGlobal Tokyo
        </a>
      </footer>
    </div>
  );
};

export default Home;
